platform :ios, '9.0'

target 'quickstart-swift' do
  use_frameworks!
  # Pods for quickstart-swift
  pod 'immersive-reader-sdk', :git => 'https://github.com/microsoft/immersive-reader-sdk.git'

  target 'quickstart-swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
